language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

notifications:
  email:
    recipients:
      - micro@fastmail.com
    on_success: change
    on_failure: change
