[package]
name = "disco-rs"
description = "An implementation of the Disco cryptographic protocol framework in pure Rust"
version = "0.1.0"
authors = ["Michael Rosenberg <micro@fastmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["crypto", "strobe", "disco", "protocol", "framework"]

[dependencies]
curve25519-dalek = "0.17" # Version required by x25519-dalek
rand = "0.5"
strobe-rs = "0.3"

[dependencies.x25519-dalek]
version = "0.2"
default-features = false
features = ["u64_backend"]
